### ISSUE TITLE
It refreshes on every scroll and it appends the ListView

### ISSUE THREAD

**Issue by aemxn** [nicolasjafelle/RefreshMenuItem#1]
This library worked well for me. But when I click the refresh menu item, it doesn't clear the ListView instead it appends the data at the bottom of the ListView.

One more problem is once I clicked the menu item, after every scroll I made, it refreshes it (indeterminate progress shown).

Some info I could give is I'm using `onScrollListener` to load more item at the bottom of the ListView, if it helps..

**Comment by nicolasjafelle** [comment]
@aimanbaharum Hello!! Thanks for your feedback. This library is not related to listviews or any viewgroup/view in particular. It just shows only the indeterminate progress in the ActionBar and methods to show and dismiss it.
I think you are having troubles with yours ListView implementation, what library are you using? I made another small library for this kind of things, take a look at PagingListView, it could resolve your problem, if not, put all the code here and I will investigate more deeply!!

PagingListView: https://github.com/nicolasjafelle/PagingListView

Hope it helps!
